version: '3.5'

services:
  web:
    build:
      context: ./docker/web
      args:
        uid: ${UID}
    container_name: quinta_web
    restart: always
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html/
#      - ./docker/web/apache2.conf:/etc/apache2/apache2.conf
#      - ./docker/web/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 80:80
    networks:
      - backend
  db:
    image: mysql:8
    container_name: quinta_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/db/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootsecret
      - MYSQL_DATABASE=quinta
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=secret
    ports:
      - 3306:3306
    networks:
      - backend

networks:
  backend:
    name: backend-network
